server:
  port: 9092
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.187.128:2181
  protocol:
    name: dubbo
    port: 20882
spring:
  datasource:
    url: jdbc:mysql:///shopping
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver