server:
  port: 8084
dubbo:
  application:
    name: sso_web
  registry:
    address: zookeeper://192.168.187.128:2181
  consumer:
    check: false
spring:
  redis:
    host: 192.168.187.128
    password: root
  rabbitmq:
    host: 192.168.187.128
    username: admin
    password: admin
    virtual-host: /admin
    port: 5672